services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  db-migrate:
    build:
      context: .
      dockerfile: prod.Dockerfile
      target: deps
    command: sh -c "npm run db:migrate"
    # todo: Shouldn't be necessary
    env_file:
      - .env
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: sh -c "node server.js"
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      db-migrate:
        condition: service_completed_successfully

  seed:
    build: .
    command: sh -c "npm run db:seed"
    # todo: Shouldn't be necessary
    env_file:
      - .env
    working_dir: /app
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    profiles:
      - seed

volumes:
  postgres_data:
