services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build:
      context: .
      target: dev
    env_file: .env
    # Use inter-container communication to reach `db`
    environment:
      - DATABASE_URL=sqlserver://db;database=postgres;user=sa;password=Password123;encrypt=true;TrustServerCertificate=true;
      - DATABASE_URL_UNPOOLED=sqlserver://db;database=postgres;user=sa;password=Password123;encrypt=true;TrustServerCertificate=true;
    ports:
      - 3000:3000
    develop:
      watch:
        - path: .
          target: /app
          action: sync

volumes:
  mssql_data:
