services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build:
      context: .
    env_file: .env
    # Use inter-container communication to reach `db`
    environment:
      - DATABASE_URL=sqlserver://db;database=personal-finance-app;user=sa;password=Password123;encrypt=true;trustServerCertificate=true;
    ports:
      - 3000:3000

volumes:
  mssql_data:
