services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build:
      context: .
    environment:
      DATABASE_URL: sqlserver://db;database=personal-finance-app;user=sa;password=Passw0rd;encrypt=true;trustServerCertificate=true;
      SESSTION_SECRET: s3cret
    ports:
      - 3000:3000

volumes:
  mssql_data:
